# Generated by Django 4.0.6 on 2022-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsrecord',
            name='fact_hours',
            field=models.FloatField(),
        ),
    ]
