# Generated by Django 4.0.6 on 2022-07-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0002_alter_tsrecord_fact_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsrecord',
            name='accepted_hours',
        ),
        migrations.AddField(
            model_name='tsrecord',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
