# Generated by Django 4.0.6 on 2022-07-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0005_delete_person_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
